# ddev generic/default/php config for apache2

# If you want to take over this file and customize it, remove the line above
# and ddev will respect it and won't overwrite the file.
# See https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#custom-apache-configuration
<VirtualHost *:80>
  RewriteEngine On
  RewriteCond %{HTTP:X-Forwarded-Proto} =https
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
  RewriteRule ^(.+[^/])$ https://%{HTTP_HOST}$1/ [redirect,last]

  SetEnvIf X-Forwarded-Proto "https" HTTPS=on

  ServerAdmin webmaster@localhost
  DocumentRoot /var/www/html
  <Directory "/var/www/html/">
    AllowOverride All
    Allow from All
  </Directory>

  ErrorLog /dev/stdout
  CustomLog ${APACHE_LOG_DIR}/access.log combined

  # Proxy WordPress and uploads to production (local dev only)
  ProxyPass /wordpress/ https://www.bosphilly.org/wordpress/
  ProxyPassReverse /wordpress/ https://www.bosphilly.org/wordpress/
  ProxyPass /wp-content/uploads/ https://www.bosphilly.org/wordpress/wp-content/uploads/
  ProxyPassReverse /wp-content/uploads/ https://www.bosphilly.org/wordpress/wp-content/uploads/
  SSLProxyEngine on

  # Increase allowed field size for large cookies header.
  LimitRequestFieldSize 16380

  #Include conf-available/serve-cgi-bin.conf

  # Simple ddev technique to get a phpstatus
  Alias "/phpstatus" "/var/www/phpstatus.php"
  Alias "/xhprof" "/var/xhprof/xhprof_html"
  <Directory "/var/xhprof">
    Options Indexes
    AllowOverride None
    Require all granted
  </Directory>

</VirtualHost>

<VirtualHost *:443>
  SSLEngine on
  SSLCertificateFile /etc/ssl/certs/master.crt
  SSLCertificateKeyFile /etc/ssl/certs/master.key

  RewriteEngine On
  RewriteCond %{HTTP:X-Forwarded-Proto} =https
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
  RewriteRule ^(.+[^/])$ https://%{HTTP_HOST}$1/ [redirect,last]

  SetEnvIf X-Forwarded-Proto "https" HTTPS=on

  ServerAdmin webmaster@localhost
  DocumentRoot /var/www/html
  <Directory "/var/www/html/">
    AllowOverride All
    Allow from All
  </Directory>

  ErrorLog /dev/stdout
  CustomLog ${APACHE_LOG_DIR}/access.log combined

  # Proxy WordPress and uploads to production (local dev only)
  ProxyPass /wordpress/ https://www.bosphilly.org/wordpress/
  ProxyPassReverse /wordpress/ https://www.bosphilly.org/wordpress/
  ProxyPass /wp-content/uploads/ https://www.bosphilly.org/wordpress/wp-content/uploads/
  ProxyPassReverse /wp-content/uploads/ https://www.bosphilly.org/wordpress/wp-content/uploads/
  SSLProxyEngine on

  # Increase allowed field size for large cookies header.
  LimitRequestFieldSize 16380

  #Include conf-available/serve-cgi-bin.conf
  # Simple ddev technique to get a phpstatus
  Alias "/phpstatus" "/var/www/phpstatus.php"
  Alias "/xhprof" "/var/xhprof/xhprof_html"
  <Directory "/var/xhprof">
    Options Indexes
    AllowOverride None
    Require all granted
  </Directory>

</VirtualHost>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
